### ISSUE TITLE
Checkbox to toggle log-transformed axes?

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEE#263]
A question from a presentation I gave.

Things that immediately pop in mind to be careful about:
- do point selections behave well in the transformed space? 
- such checkboxes should be disabled/hidden in the presence of negative values on that axis

**Comment by csoneson** [comment]
We got the same request during EuroBioc last week actually :)

**Comment by federicomarini** [comment]
I think Christian was referring more to get a button to transform the raw data to log2 normalized values. To which my immediate reply was to use a separate assay slot... I don't see how fast that can become prohibitive in terms of memory?

**Comment by kevinrue** [comment]
@federicomarini I think that with HDF5 the memory issue of any number of assays is mute (perhaps even metadata can be streamed from an HDF5 file actually).

My initial reaction was the same as you - precompute a different assay.
However, the question was from a CyTOF user more specific about switching between the two "views" rather than "scales" (i.e., show the actual values, but on a visual log-scale), which sounded like a common thing to do in CyTOF (I personally can't speak from experience).

What I'm thinking here is rather simple: the checkbox would toggle `+ scale_[xy]_log10()`.

**Comment by LTLA** [comment]
A separate assay would be trivial, even for HDF5. Set it up as a DelayedArray and you can get a free log2 transformation that is present without actually performing the calculation explicitly.

And this would be the simplest approach. You really don't want to add a scale option, because then we'd have to add a scale option for the colours, and for the sizes, and so on.

**Comment by LTLA** [comment]
Onto the actual questions:

> do point selections behave well in the transformed space?

I don't even know what this means. A selection is a selection in whatever space it was made in. There's nothing more to it; what does it mean to not behave well, anyway?

> such checkboxes should be disabled/hidden in the presence of negative values on that axis

I can have whatever negative values I like, e.g., arcsinh transform.

**Comment by federicomarini** [comment]
> what does it mean to not behave well, anyway?
I think this is related to the fact of how the brush is "picked" if the axis is not linear. I recall there were some issues in previous versions, and I did not try out whether this changed recently.

**Comment by LTLA** [comment]
The rectangular selections would be fine for monotonic transformations.

It's true that the lasso might do weird things with respect to the convex hull, because the user will think that selections are made in log-space but the calculation is done in the raw space (assuming shiny returns coordinates in the latter). Probably easier to just have a new assay, you'd need to do another selection anyway so this fits in most easily with our current paradigm.

**Comment by kevinrue** [comment]
Closing at it seems easy enough to just add a log-transformed assay
