### ISSUE TITLE
High quality figure export with support for various filetypes

### ISSUE THREAD

**Issue by robertamezquita** [iSEE/iSEE#338]
Working with several biological collaborators using iSEE, a few things came up as must-haves to make iSEE a part of their regular routine. Amongst them, one feature that would be a gamechanger  would be the ability to generate high quality PNGs/PDFs directly from the interface itself.

**Comment by LTLA** [comment]
Can't they just right click and "save as"?

**Comment by federicomarini** [comment]
I guess Rob would rather wish a button to control the output via some `ggsave` tweaking (which would unlock the freedom to select device, size, & co).
I also got this request from a couple of collaborators. From the feasibility I think we all agree there should be no big issue (_knocks on wood_)

**Comment by robertamezquita** [comment]
Exactly Federico, its mostly to be able to save something in vector
format/create a high res/high dpi version of a figure (the "Save As..."
works, but creates very small figures that aren't usable for
powerpoints/polishing into publication quality)

**Comment by LTLA** [comment]
As usual, the difficulty of the task at hand is underestimated.

Note to future self or @kevinrue: this involves creating another generic to handle the output of `.generateOutput` and create a plot on the current graphics device. For `DotPlot`s and other ggplot-powered panels, this just involves `print(out$plot)`, but for the heatmaps this is more involved and involves doing the full `draw` invocation.

Then, when someone requests a PDF of all plots, we just loop through the panels, call `.generateOutput()` and then call the new generic to save the plots to a single PDF. We may even be able to modify the height, width and whether a plot should be included at all, in a similar manner to the panel organization modal. 

In theory it is also possible to cache more carefully so that we don't have to re-run `.generateOutput()`. Not sure the efficiency boost is worth the potential bugs that might introduce, though.
