### ISSUE TITLE
Dynamic dataset selection

### ISSUE THREAD

**Issue by frenkiboy** [iSEE/iSEE#370]
**Describe the solution you'd like**
Would it be possible to enable dynamic selection of datasets - i.e. a user provides a list of objects that can be loaded into iSEE, and selects one of them which is then visualized?
And the datasets can be exchanged within the running app.

**Describe alternatives you've considered**
Setting up multiple instances with multiple datasets

Best regards, 

Vedran Franke

**Comment by LTLA** [comment]
> Would it be possible to enable dynamic selection of datasets - i.e. a user provides a list of objects that can be loaded into iSEE, and selects one of them which is then visualized?

Yes, but it is a more work than you might expect. You will have to create a custom landing page (see the second example in `?createLandingPage` for a good case study of populating with a selectize with the **scRNAseq** datasets). This will then allow you to select datasets to load into the app, and it's a good solution if you're setting up a Shiny app on a server for other people to play with; but if you just have a few datasets and you want to look at them on your own computer, honestly speaking it's easier to just open up a few R sessions and run `iSEE` on each of those SE's individually.

(**Note:** the `createLandingPage` function requires the BioC-devel version of the package, or at least the version on this repository, rather than the version available on BioC-release.)

> And the datasets can be exchanged within the running app.

Well. Sort of. If you use the landing page approach above, and you refresh the browser, you go back to the landing page where you can pick a new dataset. Obviously, though, this wipes out the state of the application state for the dataset you were previously exploring. Maybe you care, maybe not.

The other solution is to - again - open up several R processes, run a whole bunch of `iSEE` instances and use the in-built functionality in your browser to switch across tabs. If you plan to do this often, you can make it easier for yourself by using one R process to save all of your SEs into RDS files, and then writing a shell script that does something like:

```sh
#!/bin/bash
Rscript -e "iSEE::iSEE(readRDS(commandArgs(trailing=TRUE)))" $1
```

So if you named this script something like `iSEE.sh`, you could do stuff like:

```sh
$ ./iSEE.sh my_saved_SE.rds
```

Click on the location provided by `Listening on...`, and boom, new `iSEE` instance. And you can just do this again and again for every SE that you save in your "master" R process.

> Setting up multiple instances with multiple datasets

Yes, this is the simplest solution. At some point we may create a wrapper that expedites this by creating parallel processes that silently run isolated instances of `iSEE`. But that's pretty tricky stuff that requires care to avoid problems like fork bombs, so don't hold your breath for it.

**Comment by frenkiboy** [comment]
Dear Aaron, 

Thank you so much for your prompt reply. I'm dealing with computationally challenged users, and it's much easier for me to setup online instances using the shiny server. Because the number of served connections is limited, it would be extremely nice if we could have the clump several datasets into one instance.

Will try constructing the landing page.

Best, 

Vedran

**Comment by LTLA** [comment]
An additional advanced option is possible by abusing **iSEE**'s faceting system. 

1. Set up the landing page to allow users to pick multiple datasets, e.g., with a `selectizeInput`.
2. In the landing page observer, construct a single SE by `cbind`ing all of the selected SEs together. Hopefully there is a non-trivial number of shared features across the selected SEs. You will have to make some decision about what to do with mismatched `colData` fields, and you will also have to fiddle with the dimensionality reduction results to lie within the same magnitude of values. (Both of these things generally can be done ahead of time for efficiency.)
3. Add a `colData` field specifying the dataset of origin for each column in the merged object.
4. Start up all plots with `FacetRows="dataset"` (or whatever you called the field in **3**). This will create plots that are faceted by dataset, allowing you to visualize multiple datasets at once.

Hopefully, your users will not try to turn off the faceting as this would make nonsense plots.

**Comment by LTLA** [comment]
I'm going to assume that one of those solutions was satisfactory.
