### ISSUE TITLE
Edit User Interface

### ISSUE THREAD

**Issue by kikegoni** [iSEE/iSEE#416]
Hey all,

First of all thanks and congratulations for developing iSEE. It is super useful and the last version is amazing. 

We are interested in doing very minor edits to the user interface. Is it a function or a way to do it?

For example we would like to rename the "Feature name" in the Visual field under each panel to be named "Gene name". Actually in the package this value can be printed as:

```r
iSEE:::.colorByFeatNameTitle
[1] "Feature name"
```
But since it is an internal variable I am not able to change its content with:
```r
 iSEE:::.colorByFeatNameTitle <- "Gene name"
Error in iSEE:::.colorByFeatNameTitle <- "Gene name" : 
  could not find function ":::<-"
```

Is it a way to perform that? 

Thank you so much in advance for any help you might be able to provide.

Kike

**Comment by LTLA** [comment]
No, there isn't. The concept of a "feature" is embedded throughout a lot of the **iSEE** code, interface and documentation. If we chose to allow people to change it, we would have to generalize that change everywhere otherwise you'd have parts of your interface saying "feature" (e.g., the `FeatureAssayPlot`) and other parts saying "gene". This would be far too much effort.

I don't think it's much of a struggle to have to remember that your features are genes.

**Comment by kikegoni** [comment]
Hey @LTLA ,

Sure, perfect. I can see that,

Thanks anyway for implementing the package!
