### ISSUE TITLE
Store panel outputs in objects with different names

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEE#443]
**Is your feature request related to a problem? Please describe.**
In the 'Extract the R code' modal, all ggplot panels store their output in an object named `dot.plot`, all tables in an object named `tab`, and ComplexHeatmap panels in an object named `hm`.
This means that one cannot run the whole script _and then_ display each plot/table/heatmap.
Instead the code of each panel must be run individually, the output shown _and then_ run the code for the next panel.

**Describe the solution you'd like**
Each panel should store its output in a uniquely named object, e.g. `<encodedPanelName><panelID>`.

**Describe alternatives you've considered**
None yet.

Note that from a quick inspection, this doesn't seem to affect the export of panel outputs, which directly uses the object without relying on the variable name.
That said, it is worth checking whether any other part of the code relies on the variable names defined in the script reported in the  'Extract the R code' modal.

**Additional context**
n/a

**Comment by LTLA** [comment]
`.generateDotPlot` is contractually obliged to return a dot plot in the `dot.plot` variable. One could add a command to create a unique variable, but that means that subclasses that `callNextMethod()` in their `.generateDotPlot` are now obliged to operate on both the `dot.plot` and the new variable to implement extra features.

Any changes should be limited to the code tracker. Unfortunately, the tracker knows nothing about which panels are plots that need this reassignment. It cannot use `pObjects$varname` because that describes the plot contents rather than the `ggplot` object itself. You would have to define a new generic like `.appendTrackerCode`.

**Comment by kevinrue** [comment]
Dropping unless someone other than me actually asks for it
