### ISSUE TITLE
ComplexHeatmap autocomplete functionality

### ISSUE THREAD

**Issue by daymecita** [iSEE/iSEE#586]
Hello!
I had been using the Heatmap on iSEE with the autocomplete functionality when adding features to visualize. There used to be an input box called "Features", at least until the version 1.5. When I updated to version 2.5 and later, the heatmap was replaced by the ComplexHeatmap which is better, BTW. However, if one wants to add genes manually it has to be using the "Edit feature names" editor and type there the gene names.  It is perfect for copying and pasting from an external list, but if instead, I want to visualize some genes I know by heart, I would like to have the autocomplete functionality to help me adding the gene names. Is it possible to have it on the editor? 

Thank you for your amazing work :)

**Comment by kevinrue** [comment]
Hi,

You wouldn't have any screenshot or link to that earlier behaviour by any chance? Digging up the source code of iSEE at the time and/or re-installing the correct version of R/Bioconductor/iSEE is a bot of a pain.

I honestly can't remember how the app looked and behaved at the time.

From your description, it sounds like the 'input box' that you mention was a `selectizeInput` instead of an `aceEditor`.
The former easily offers autocomplete, as it knows all the options available.
The latter has an `autoComplete` argument, which clearly would take a bit of work to define autocompletion options in the editpor
https://github.com/iSEE/iSEE/blob/70a793cc867a142deedd6e37131d23c9e4605a78/R/observers_modal.R#L84 

Reference for whenever I have time to look into this further:

- `?shinyAce::aceEditor`
- `?shinyAce::aceAutocomplete`

**Comment by daymecita** [comment]
Hello! 
Yes, the input box I meant was the selectizeInput. Actually, in one of the iSEE vignettes it says:
"User can select features (rows) to display from the selectize widget (which supports autocompletion), or also via other panels, like row data plots or row data tables. In addition, users can rapidly import custom lists of feature names using a modal popup that provides an [Ace editor](https://ace.c9.io/) where they can directly type of paste feature names, and a file upload button that accepts text files containing one feature name per line."
However, the selectize widget is not there, and the file upload button neither. Am I missing something? 
Thank you for looking into this :)

**Comment by daymecita** [comment]
I also thought that maybe instead of having an extra selectize widget to add features, we could have the autocomplete function on the ace editor.

**Comment by kevinrue** [comment]
https://youtu.be/cv8UwzFKw5E :)

**Comment by kevinrue** [comment]
@daymecita 

I forgot to say: please let me know if it all works for you as expected. Feedback always welcome even after I close the issue, as I only tested it in a single scenario. Plus, I'm always keen to know that it works as expected in the user's environment too!

**Comment by daymecita** [comment]
The heatmap looks awesome. It helps a lot having the autocomplete functionality on the editor. 
Honestly iSEE is a great tool but the team working actively behind it makes it even better. Thank you so much :)

**Comment by kevinrue** [comment]
Ok, excellent: glad to hear that it works fine for you too then!

Happy to help develop features that make iSEE better for users, not just us developers ☺️
