### ISSUE TITLE
Complex Heatmap too slow

### ISSUE THREAD

**Issue by daymecita** [iSEE/iSEE#616]
Hello!
I am working with an SCE object that contains ~500K cells and 30K genes. I want to plot 120 genes on the heatmap upon the app start by using iSEE(sce, initial = ComplexHeatmapPlot(CustomRowsText=genes)) but I get this error: Warning: Error in h: error in evaluating the argument 'x' in selecting a method for function '.refineParameters': invalid type or length for slot name.

I can make it work by modifiying the ComplexHeatmap class and adding to the refineParameters function the following:  
slot(x, .heatMapFeatNameText) <- paste(unique(top5$gene_name), collapse = '\n'), where top5 are the genes I read from a file. However the heatmap takes several minutes to render (~5 mins or more). I don't know why it is so slow but I noticed that the generateOutput function is called twice. Why is that necessary? This might be slowing the rendering down more. Don't you think? 

I'd really appreciate if you could look into this when yu have time, since I am struggling using the heatmap with big objects. 

Cheers!
Dayme

**Comment by kevinrue** [comment]
Hi

### CustomRowsText

`CustomRowsText` should not be the R vector of genes, but a single character scalar that represents the content of a text editor where each of those genes would be on a separate row, i.e. it should look like this:

```
genes <- "gene1\ngene2\ngene3\ngene4\ngene5\ngene6\ngene7\ngene8\ngene9"
```

not like that:

```r
genes <- c("gene1, "gene2", ...)
```

That's because this slot is used to populate (and track) the live text editor in the iSEE app.

### Rendering

The heatmap panel is naturally the most intensive panel to generate. 

We are largely dependent on the performance of the ComplexHeatmap package (which is my personal favorite generally in terms of performance as well as looks), as well as the rendering of the resulting figure in the Shiny app.

I agree that it is strange that the `generateOutput` function is called twice. It is probably accidental and needs checking. 

I'm not sure what else can be done to speed up the rendering of the heatmap.
It does remind me that we have not implemented visual downsampling for the ComplexHeatmap panel, which could help reduce the workload for the ComplexHeatmap package, but thinking about it now, downsampling a heatmap is whole different job to scatter plots (it would not be about overplotting anymore, but rather about proportionally downsampling clusters of rows and columns, I think).

I do have other priority jobs in the near future, so I can't promise a timeline for this.

**Comment by kevinrue** [comment]
Closing as the latest message seems to have solved it.
