### ISSUE TITLE
Allow users to suppress the violin plot for smaller datasets

### ISSUE THREAD

**Issue by tomsing1** [iSEE/iSEE#619]
A violin plot is great when the number of samples / cells is large, but for bulk experiments from smaller experiments, they are not as helpful (see example below). 
![screenshot](https://user-images.githubusercontent.com/10490984/216464901-42d5c4c4-cbf6-4e0e-b34b-39ff0e21eabf.png)

It would be great for users to be able to suppress the violin plot (just like contours are optional for scatter plots), e.g. to just receive a scatter plot of the continuous y-variable vs the categorical x-variable.

**Comment by kevinrue** [comment]
While I look at it now, it just reminds me that violin plots are not a class of panels, but rather a geometry that is applied to various `DotPlot` panel classes when one axis is discrete and the other one is continuous.

It might take a bit of extra effort to make sure this new feature integrates nicely with all affected panel classes and doesn't create any undesirable interaction.

**Comment by kevinrue** [comment]
Note to self (insight for wannabe contributors):

```bash
$ grep geom_violin R/*
```

Reveals a single line responsible for the `geom_violin()`.
https://github.com/iSEE/iSEE/blob/master/R/plotting.R#L331

The `.violin_plot()` function receives an instance of a `DotPlot` class that contains the UI inputs for that panel.

As a consequence, the functionality initially requires a simple checkbox toggling the violin as  a TRUE/FALSE value.

Where it gets more complicated is that the checkbox is only relevant when the X/Y axes are a combination of discrete/continuous variables that do indeed result in a violin plot. Namely:

* two continuous axes result in a scatter plot that doesn't display violins, and thus the checkbox for violins should be hidden.
* two discrete axes result in a Hinton plot that doesn't display violins, and thus the checkbox for violins should be hidden.

I have to dig further, as this feels a bit tricky: we are talking about UI choices (X/Y) axes that need to be checked against the data set (without generating a new plot) to verify whether other UI elements should be shown/hidden, before applying against all those UI settings again to the data set to actually generate the plot.

I just want to make sure that this seemingly simple feature request doesn't introduce performance issues due to re-evaluating the same things multiple times, potentially slowing down the app when it comes to refreshing the UI.

One option would be to hijack the checkbox "Add contours (scatter only)",  considering violins as contours. That checkbox is currently visible no matter what the geometry of the plot is, with only the "scatter only" warning to inform and reassure users.

I suggest going with the quick fix of renaming that checkbox "Add contour / violin" and using it for both scatter and violin plots.

The main issue with that being that the default setting of that checkbox conflicts:

* Typically scatter plots look better without the contour, represented by the current default (unchecked box)
* Typically violin plots look better with the contour (... the violin), which would push for a default checked box

@csoneson ?

**Comment by csoneson** [comment]
I agree that violins are not always very informative, and that it would be nice to be able to deactivate them. In addition to the default on/off state, there is also a difference between the contours and the violins in the default color. I'm wondering if it's not as easy to just have an additional checkbox for the violins (which would only apply to the violin plots, just like the contours now only apply to the scatter plots).

**Comment by kevinrue** [comment]
Add a  checkbox for users to manually toggle violins
